### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Aub-C** [cronyo/cronyo#3]
Hello,

I'm running into issues with the installation. I've tried installing on Mac and on Ubuntu. I can't seem to get past the error below. Any idea what the issue may be?

```
ubuntu:~$ cronyo configure
[.] Using config /home/ubuntu/.cronyo/config.yml
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cronyo", line 5, in <module>
    from cronyo.cli import cli
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cronyo/cli.py", line 13, in <module>
    import cron_rules
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cronyo/cron_rules.py", line 15, in <module>
    NAMESPACE = config.get("namespace", "cronyo")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by gingerlime** [comment]
Looks like you're using python2 ? cronyo supports python > 3 so I suspect this might be the reason...

**Comment by Aub-C** [comment]
That is what I was thinking as well. However, when I try to install from python 3.7 I run into this error: 

`[.] generating new config /home/ubuntu/.cronyo/config.yml
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cronyo", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/cli.py", line 123, in configure
    generate_config(config_filename)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/config.py", line 57, in generate_config
    config_file.write(_config_template())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/config.py", line 46, in _config_template
    template = open(resource('cronyo', 'config.yml.template'), 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/config.yml.template'`

**Comment by Aub-C** [comment]
And when I run cronyo configure a second time:

`[.] Using config /home/ubuntu/.cronyo/config.yml
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cronyo", line 7, in <module>
    from cronyo.cli import cli
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/cli.py", line 8, in <module>
    from cronyo import cron_rules
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cronyo/cron_rules.py", line 15, in <module>
    NAMESPACE = config.get("namespace", "cronyo")`

**Comment by gingerlime** [comment]
@Aub-C thanks for your report. Can you try with cronyo 0.4.1 ? Should fix this.

**Comment by Aub-C** [comment]
Thank you for the update. I've run into another error. 

Now I get:

On Mac: `/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'cronyo': [Errno 2] No such file or directory`

On Ubuntu:
`/usr/bin/python3: can't open file 'cronyo': [Errno 2] No such file or directory`

**Comment by gingerlime** [comment]
I’m sorry that the first impression you’re having is broken. Are you able to try it with pyenv (that’s what I’m using)? And can you post the full trace with the command that you’re typing?

I’ll try to do more testing on platforms without pyenv as well to debug this.

**Comment by gingerlime** [comment]
I just tested it on a fresh ubuntu 18.04 with python3 and didn't get the same error (spotted something else related to yaml, which I'll look into, but not this error).

If you can provide a bit more details on how to reproduce I would really appreciate it.

**Comment by Aub-C** [comment]
Could have been a python misconfiguration or dependency issue on my end. I went through a fresh ubuntu 18.04 install using 'pyenv' as you suggested and it worked. Thank you for the assistance.

**Comment by gingerlime** [comment]
Great to hear, @Aub-C. Thanks for reporting it. It helped fix a couple of bugs :)

If you bump into anything else, I'd be happy to help!
